name: AuthMeVelocity
authors: [xQuickGlare, 4drian3d]
version: ${project.version}
main: com.glyart.authmevelocity.spigot.AuthMeVelocityPlugin
depend: [AuthMe]
soft-depend: [MiniPlaceholders]
# pls, dont use outdated versions, use 1.16.5+
api-version: 1.13