name: AuthMeVelocity
version: '${version}'
main: io.github._4drian3d.authmevelocity.paper.AuthMeVelocityPlugin
bootstrapper: io.github._4drian3d.authmevelocity.paper.AuthMeVelocityBootstrap
description: AuthMeReloaded Support for Velocity
authors:
  - xQuickGlare
  - 4drian3d
website: https://modrinth.com/plugin/authmevelocity
api-version: '1.20'
folia-supported: true
dependencies:
  server:
    MiniPlaceholders:
      required: false
      load: BEFORE
    AuthMe:
      required: true
      load: BEFORE
