name: AuthMeVelocity
version: "${version}"
main: io.github._4drian3d.authmevelocity.paper.AuthMeVelocityPlugin
description: AuthMeReloaded Support for Velocity
authors:
  - xQuickGlare
  - 4drian3d
website: https://modrinth.com/plugin/authmevelocity
depend:
  - AuthMe
api-version: 1.13
folia-supported: true
softdepend:
  - MiniPlaceholders
